\input texinfo
@setchapternewpage off
@settitle 3DViewer_v2.0. Иструкция

@node Top
@top 3DViewer_v2.0. - Визуализация в 3D формате объектных файлов .obj. 
Приложение позволяет открывать .obj файлы и проводить различные манипуляции с движением. 
А также дает возможность сохранять открытый файл в  формате bmp, jpg.

@menu
* Возможности :: Синопсис первой главы
* Использование  :: Синопсис второй главы
@end menu

@node Возможности
@chapter Возможности 3DViewer_v2.0

3DViewer_v2.0 поддерживает:
@enumerate
@item x перемещает по оси x;
@item y перемещает по оси y;
@item zoom меняет масштаб;
@end enumerate

@bye

